name: Update Checker

env:
  REPO_URL: https://github.com/sorin-ionescu/prezto.git
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */18 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source codes
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"
    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1